### ISSUE TITLE
Cache random cards to decrease random deck loading time

### ISSUE THREAD

**Issue by SethColeman50** [cs298-398f23/magic_randomizer#9]

**Comment by SethColeman50** [comment]
Download the entire scryfall database and put it in the mongo docker container with a new dockerfile, then we don't need to deal with the scryfall api random being slow.

**Comment by reyesc02** [comment]
We can just cache the entire card text list which will save on space. The scryfall api conveniently has a call for getting all cards as text format.

**Comment by SethColeman50** [comment]
we can close the issue once we merge your pull request
